### ISSUE TITLE
上传用户头像失败（提交问题示例）

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#1]
问题描述：上传用户头像失败
类型: 功能问题          （功能问题 / UI问题 / 其他）
优先级：高           （高 / 中 / 低）
详情：组织视图下， 点击右上角头像进入“Profile”，上传头像“Profile Photo”，上传失败。
截图：
![image](https://user-images.githubusercontent.com/20469925/63496701-f4d25480-c4f4-11e9-93b9-bd3be248c6f4.png)

**Comment by dodoroy** [comment]
上传图片接口更改了地址
