### ISSUE TITLE
打开的组织不是自己搜索的组织

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#10]
问题描述：打开的组织不是自己搜索的组织
类型：功能问题
优先级：高
详情：输入ssh，打开的不是ssh这个组织，显示的是comunion的组织。
![image](https://user-images.githubusercontent.com/20469925/63560162-930efa80-c587-11e9-8796-d65f5c1bde19.png)
![image](https://user-images.githubusercontent.com/20469925/63560172-9dc98f80-c587-11e9-94fd-27a6060e8516.png)

**Comment by dodoroy** [comment]
已修改，之前左上角显示的是咱们这个产品comunion及其logo
