### ISSUE TITLE
组织视图页面，多出一块comunion的显示

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#11]
问题描述：组织视图页面，有多余的内容
类型：UI问题
优先级：高
详情：组织视图页面，多了一块Comunion的显示，如图
![image](https://user-images.githubusercontent.com/20469925/63560263-f567fb00-c587-11e9-8175-1fdbaeb746d7.png)

**Comment by dodoroy** [comment]
已隐藏
