### ISSUE TITLE
组织视图，隐藏contract

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#12]
问题描述：组织视图，隐藏contract
类型：功能问题
优先级：高
详情：组织视图，隐藏contract。一期不涉及到contract，先隐藏，以后才会用到。
![image](https://user-images.githubusercontent.com/20469925/63560397-77582400-c588-11e9-96db-3b4f2dd3e209.png)

**Comment by dodoroy** [comment]
已隐藏
