### ISSUE TITLE
Dashboard，填写的social media没有显示，再次编辑提示network error

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#13]
类型：功能问题
优先级：高
详情：Dashboard，填写的social media没有显示，再次编辑提示network error
![image](https://user-images.githubusercontent.com/20469925/63560506-d61d9d80-c588-11e9-85cf-deef4dc5e2c0.png)

**Comment by ShirleyZmj** [comment]
可以再测试一下嘛？我自己好像没有复现， social media的种类是不是有限制？你创建的是哪个社交媒体呢

**Comment by sshnii** [comment]
![image](https://user-images.githubusercontent.com/20469925/65501318-638b3f00-def3-11e9-830a-22993d47e704.png)
![image](https://user-images.githubusercontent.com/20469925/65501332-69812000-def3-11e9-96de-09ee38a7e36b.png)
![image](https://user-images.githubusercontent.com/20469925/65501451-9df4dc00-def3-11e9-8cf4-8bf556849b6f.png)

我创建了两个，但是保存后是空的。network error 的问题已经没有了。首字母改为大写吧，Facebook、Twitter这种，小写显得很不专业
