### ISSUE TITLE
Dashboard，左侧导航栏，除了Dao info 和 Team manager 外，其他入口先隐藏

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#14]
类型：UI问题
优先级：高
详情：Dashboard，左侧导航栏，除了Dao info 和 Team manager 外，其他入口先隐藏
![image](https://user-images.githubusercontent.com/20469925/63560575-1c72fc80-c589-11e9-8cc8-a22ddde4df1c.png)

**Comment by dodoroy** [comment]
已隐藏
