### ISSUE TITLE
Profile，输入的是正确的地址，但是提示是无效的地址

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#15]
类型：功能问题
优先级：高
详情：进入“profile”-“wallet”-“add address”，输入正确的钱包地址，提示是无效的地址
![image](https://user-images.githubusercontent.com/20469925/63560710-973c1780-c589-11e9-9d89-38edfb670cf4.png)

**Comment by PercivalZhang** [comment]
看看是不是匹配规则有问题？

**Comment by ShirleyZmj** [comment]
/^(0x)(\d|\w){40}/i  前端匹配规则是这个，那正确的匹配规则是什么呀

**Comment by sshnii** [comment]
这个去掉了BTC钱包，ETH钱包匹配规则是可以的，这个可以关闭了
