### ISSUE TITLE
注册个人账户时密码长度无限制

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#16]
问题描述：注册个人账户时密码长度无限制
类型: 其他
优先级：低
详情：组织视图下， 点击右上角头像注册用户，填写密码时没有长度限制。
截图：
![屏幕快照 2019-08-23 上午9 37 17](https://user-images.githubusercontent.com/40222554/63560728-a7ec8d80-c589-11e9-88e4-776c974d3db4.png)

**Comment by sshnii** [comment]
限制24个字符吧，超过了无法输入

**Comment by dodoroy** [comment]
密码添加限制：至少6个字符，最长24字符
