### ISSUE TITLE
login 与openmask的 提示问题

### ISSUE THREAD

**Issue by kering-wang** [comunion-io/lobby#19]
目前 login 相比 openmask的大按钮太小了，这个交互是先点击 login 在点击 openmask 的 
这里的交互可以在优化下 ：
![WechatIMG5672](https://user-images.githubusercontent.com/5236356/63586398-cc6d5780-c5d3-11e9-994e-e3e50904f79f.png)

**Comment by sshnii** [comment]
同 #18
