### ISSUE TITLE
文案歧义

### ISSUE THREAD

**Issue by ljjmu222** [comunion-io/lobby#2]
问题描述：文案歧义
类型: 其他
优先级：低
详情：创建新组织名字-填写新组织名字-输入框下面提示文案“Organization name does not exist”，感觉像错误提示
截图：
![image](https://user-images.githubusercontent.com/15376595/63518614-0121d600-c524-11e9-8836-8583cd140735.png)

**Comment by sshnii** [comment]
文案改为：The organization name is available.

**Comment by dodoroy** [comment]
已修改
