### ISSUE TITLE
注册流程，邮箱认证环节丢失

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#21]
问题描述：注册流程，没有了邮箱认证环节，但注册依然可以成功
类型: 功能问题
优先级：高
详情：在注册的过程中，并未出现邮箱验证环节（未出现输入邮箱验证码的页面）。记得最早一次进行注册时出现过验证环节，但今天测试注册了五次，均没有这一环节出现。
截图：
无，有视频，需要的话请联系我。

**Comment by dodoroy** [comment]
无法复现
