### ISSUE TITLE
add member -搜索已存在的用户时，没有显示用户的头像；且点击add添加，提示net error

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#22]
类型：功能问题
优先级：中
详情：
![image](https://user-images.githubusercontent.com/20469925/63679776-b60a0a80-c824-11e9-8ef6-bd544ba2bc2f.png)

**Comment by sshnii** [comment]
![image](https://user-images.githubusercontent.com/20469925/63679824-d4700600-c824-11e9-918d-5c65c742eeb6.png)

**Comment by dodoroy** [comment]
没有显示头像就是该用户尚未上传头像，出现networ error提示是因为现有服务器不是很稳定
