### ISSUE TITLE
Ver. 1.0英文文案修正

### ISSUE THREAD

**Issue by yyf19901126** [comunion-io/lobby#23]
![image](https://user-images.githubusercontent.com/11029011/63864334-3b86e980-c9e2-11e9-94ac-6619b3666ce5.png)
Comunion is a decentralized autonomous organization collaboration network. It helps companies, organizations, and individuals all around the world to create, manage, and operate their own decentralized autonomous organizations (The DAO).

![image](https://user-images.githubusercontent.com/11029011/63864518-8c96dd80-c9e2-11e9-9236-7b1cd500199b.png)
Comunion 大写

![image](https://user-images.githubusercontent.com/11029011/63864759-f7481900-c9e2-11e9-9f82-8579d732c9c9.png)
Retrieve an existing organization

![image](https://user-images.githubusercontent.com/11029011/63864878-2e1e2f00-c9e3-11e9-9d98-e1a694e2122a.png)
建议删掉

![image](https://user-images.githubusercontent.com/11029011/63864997-6291eb00-c9e3-11e9-808b-95f3fc8f49c4.png)
1. Set Organization Name
2. 取消或Organization name is unused

![image](https://user-images.githubusercontent.com/11029011/63865403-1b582a00-c9e4-11e9-8fe8-e39094c8d314.png)
1. Organization Info
2. Select carrier net
3. Educational

![image](https://user-images.githubusercontent.com/11029011/63865622-7ab63a00-c9e4-11e9-882a-bcdd19627f77.png)
1. Official Website (建议直接写Website)
2. 最好全部首字母大写，也包括前面的按钮和标题。只有灰色的小字不要首字母大写。

![image](https://user-images.githubusercontent.com/11029011/63865821-ca950100-c9e4-11e9-8863-20edd98612ae.png)
1. Personal Info
2. The initial password will be sent to this E-mail. This E-mail can be used to login to your account. 
3. You can complete your profile later after creating the organization. 

![image](https://user-images.githubusercontent.com/11029011/63866170-6a528f00-c9e5-11e9-83b6-88e908821936.png)
1. 我觉得这里是想说ERC20上币的Deploy Transaction吧
2. This is the last step : ) You will need to sign the transaction to register your organization. 
Continue with your web wallet. 
3. 两个钱包前面不要加Open了。

**Comment by sshnii** [comment]
👍👍

**Comment by sshnii** [comment]
2. The initial password will be sent to this E-mail. This E-mail can be used to login to your account.

**Comment by dodoroy** [comment]
已修改
