### ISSUE TITLE
验证码的翻译，与验证码点击后没有60s 置灰问题

### ISSUE THREAD

**Issue by kering-wang** [comunion-io/lobby#24]
![image](https://user-images.githubusercontent.com/5236356/63936250-f6ba8b80-ca91-11e9-8ea7-184139505619.png)

验证码翻译：send verify code ，取代现在那个 那么长的  

点击验证码没有置灰

**Comment by dodoroy** [comment]
已添加发送频率限制及倒计时显示，按钮显示已改为Send Verification Code（verify是动词，不合适）
