### ISSUE TITLE
发送邮箱验证码的按钮，交互问题

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#33]
问题描述：所有发送邮箱验证码的界面中，点击发送验证码，没有提示告诉用户已经发送验证码
类型: 功能问题
优先级：中
详情：所有发送邮箱验证码的界面中，输入邮箱地址点击发送验证码，点击时按钮没有交互反应，也没有提示已发送，用户不明确自己是否点击成功，系统是否已经发送验证码。最好是：
1. 在点击时给一个明显的交互提示；
2. 点击之后按钮文字变为已发送，提示用户点击成功并已成功发送验证码。
另外，这个验证码的时效是不是需要设定一下？比如在15分钟之类有效，超过时间就失效了。
![image](https://user-images.githubusercontent.com/40222554/63960525-46647b80-cac1-11e9-829c-bd005acb1b40.png)

**Comment by sshnii** [comment]
1、点击发送验证码，按钮变为倒计时：59s。倒计时期间按钮置灰不可点，倒计时结束，可重新发送 @dodoroy 。2、验证码有效期在邮件里有说明，30分钟内有效 @slashfater 。这个有效期需要看下后端是否做了限制 @PercivalZhang。

**Comment by dodoroy** [comment]
已添加发送验证码频率限制及倒计时显示
