### ISSUE TITLE
Team Manager/Profile/Account，Add Social Media 按钮 UI 问题

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#34]
问题描述：鼠标悬停在 add 上，鼠标没有变成小手
类型: UI 问题
优先级：低
详情：鼠标悬停在 add 上，鼠标没有变成小手，用户会误认为这个功能不可用，建议改成，鼠标悬停在 add 上，鼠标变成小手。
截图：
![image](https://user-images.githubusercontent.com/40222554/63990211-c0265480-cb15-11e9-9985-e1ba641c6b01.png)

**Comment by dodoroy** [comment]
已修改
