### ISSUE TITLE
Team Manager/Profile/Account，Profile Photo 问题

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#35]
问题描述：图片可以无数量限制地上传
类型: 功能问题
优先级：中
详情：我理解的这是用户头像，应该是唯一的，现在的情况是可以无限量地上传图片。如果应该是唯一的，建议设限。
截图：
![image](https://user-images.githubusercontent.com/40222554/63990448-a76a6e80-cb16-11e9-87dd-8afdff458e22.png)

**Comment by dodoroy** [comment]
只能上传一张，已添加限制
