### ISSUE TITLE
个人页面 Profile 修改个人密码缺失

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#36]
描述：个人页面 Profile 修改个人密码缺失
类型：功能
详情：个人用户登录之后，点击页面右上角的 Porfile，进入编辑个人信息编辑页面，这里面缺失一个修改密码的功能。建议@少华配合@晓慧添加一下这个功能
截图：
![image](https://user-images.githubusercontent.com/40222554/63992438-5494b500-cb1e-11e9-828e-aebf87fd9251.png)

**Comment by dodoroy** [comment]
目前修改用户密码的功能在 登陆->忘记密码 这里实现。
因为修改密码涉及到给用户邮箱发送验证码，如果要在profile里添加这个功能，需补充profile里发送验证码展示相关设计图。

**Comment by sshnii** [comment]
“修改密码”设计页面跟“忘记密码”页面的保持一致即可
