### ISSUE TITLE
添加成员，搜索时未搜索到。再次编辑时，底部提示的文案不应该跟输入的内容关联，只有点击搜索时才更新搜索结果

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#38]
类型：功能问题
优先级：中
详情：
搜索无结果，当再编辑输入框的内容时，底下的邮箱也会跟输入的内容关联，应该不变。只有点击搜索时，才更新搜索结果。
![image](https://user-images.githubusercontent.com/20469925/64065741-109bd000-cc44-11e9-87d9-704432666292.png)

**Comment by dodoroy** [comment]
已修复
