### ISSUE TITLE
成员列表页，没有显示成员的角色信息

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#39]
类型：UI问题
优先级：中
详情：

![image](https://user-images.githubusercontent.com/20469925/64065781-b9e2c600-cc44-11e9-8287-4839c254b873.png)
![image](https://user-images.githubusercontent.com/20469925/64065782-c36c2e00-cc44-11e9-95fb-6b91dad32940.png)

解决方案：
在成员的名字下边显示成员的role

**Comment by dodoroy** [comment]
已添加角色展示
