### ISSUE TITLE
目前网络不支持切换，隐藏其他网络

### ISSUE THREAD

**Issue by sshnii** [comunion-io/lobby#40]
类型：功能问题
优先级：高
详情：
![image](https://user-images.githubusercontent.com/20469925/64157007-71a3ed80-ce68-11e9-8f0b-f2a556ea0c0a.png)
解决方案：下拉框去掉两个测试网络，只显示Ethereum Mainnet
![image](https://user-images.githubusercontent.com/20469925/64157142-c0518780-ce68-11e9-9dd4-51ef0dd10ef4.png)

**Comment by sshnii** [comment]
@dodoroy

**Comment by dodoroy** [comment]
已隐藏
