### ISSUE TITLE
获取邮箱验证码按钮点击无成功状态，邮件无限制

### ISSUE THREAD

**Issue by ljjmu222** [comunion-io/lobby#5]
问题描述：获取邮箱验证码按钮点击无成功状态，邮件无限制
类型: 功能问题 / UI问题 
优先级：高
详情：1.注册组织时，获取邮箱验证码按钮点击无成功状态
截图：

**Comment by ljjmu222** [comment]
2.邮件发送未做限制，可短时间内，多次获取

**Comment by dodoroy** [comment]
已添加发送限制
