### ISSUE TITLE
Organization Info 缺少Vision字段

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#7]
问题描述：Organization Info 缺少Vision字段
类型: 其他
优先级：低
详情：注册成功之后，在组织视图的 Organization Info页面，缺少Vision的展示。
截图：
![屏幕快照 2019-08-22 下午10 22 23](https://user-images.githubusercontent.com/40222554/63523069-0aaf3c00-c52c-11e9-831e-cabde5b7982b.png)

**Comment by dodoroy** [comment]
已将Vision展示信息放在Mission和Description之间（设计图并没有vision展示部分）
