### ISSUE TITLE
官网链接 Bug

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#8]
问题描述：组织视图中官网链接打不开
类型: 功能问题
优先级：低
详情：组织视图下， 点击官网链接，弹出新窗口，网址加载失败，在官网地址前加了测试地址，例如：http://178.128.221.42/jiaty.cn。需要说明的是，在注册流程中，我填写的官网格式为：jiaty.cn（没有加 http://）。
截图：
![屏幕快照 2019-08-22 下午10 13 29](https://user-images.githubusercontent.com/40222554/63523367-9b861780-c52c-11e9-9944-287876a23bdf.png)

**Comment by slashfater** [comment]
经多次测试，如果希望网址正常显示，输入网址格式为：http://www.abcd.com 或者 http://abcd.com。必须加上http://，有没有一种方式自动识别用户是否填写http://，大多数人都不会主动填写http://，如果用户没有填写，自动给他加上。

**Comment by sshnii** [comment]
@slashfater  测试很详细 👍

**Comment by sshnii** [comment]
解决方案：

**Comment by dodoroy** [comment]
已修改
