### ISSUE TITLE
逻辑Bug

### ISSUE THREAD

**Issue by slashfater** [comunion-io/lobby#9]
问题描述：注册完成之后，编辑资料提示请先登录，逻辑上有点奇怪
类型: 功能问题 
优先级：高
详情：注册完成之后，在组织视图，点击编辑资料，提示请先登录，点击头像登录，提示输入 Email 和 Password，此时我没有 Password，我的理解是我注册了组织，但还没有注册个人账户，需要我注册一个个人账户才可以编辑资料。在逻辑上感觉有点奇怪。
截图：无

**Comment by sshnii** [comment]
这个注册组织后，仍需要用户自己登录。密码已发到注册组织时填写的邮箱，可以使用密码登录。注册组织时填写邮箱，底部有文案说明的。
